app:
  jwtExpirationInMs: 604800000
jwt:
  secret: MyScret
logging:
  level: error
  level.org.hibernate: ERROR
  level.org.hibernate.SQL: debug
  level.org.prime: INFO
  level.org.springframework.web: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
server:
  port: 7777
spring:
  application:
    name: Test
  data:
    mongodb:
      database: syed-starter
      host: localhost
      port: 27017
  jackson:
    serialization:
      INDENT_OUTPUT: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
